config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :insta_users
  resources :insta_posts
  resources :users do
    resources :posts
  end
  root "articles#index"

  resources :articles do
    resources :comments
  end
end

app/models/insta_post.rb
class InstaPost < ApplicationRecord
end

app/controllers/insta_posts_controller.rb
class InstaPostsController < ApplicationController
  before_action :set_insta_post, only: %i[ show edit update destroy ]

  # GET /insta_posts or /insta_posts.json
  def index
    @insta_posts = InstaPost.all
  end

  # GET /insta_posts/1 or /insta_posts/1.json
  def show
  end

  # GET /insta_posts/new
  def new
    @insta_post = InstaPost.new
  end

  # GET /insta_posts/1/edit
  def edit
  end

  # POST /insta_posts or /insta_posts.json
  def create
    @insta_post = InstaPost.new(insta_post_params)

    respond_to do |format|
      if @insta_post.save
        format.html { redirect_to insta_post_url(@insta_post), notice: "Insta post was successfully created." }
        format.json { render :show, status: :created, location: @insta_post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @insta_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /insta_posts/1 or /insta_posts/1.json
  def update
    respond_to do |format|
      if @insta_post.update(insta_post_params)
        format.html { redirect_to insta_post_url(@insta_post), notice: "Insta post was successfully updated." }
        format.json { render :show, status: :ok, location: @insta_post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @insta_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /insta_posts/1 or /insta_posts/1.json
  def destroy
    @insta_post.destroy

    respond_to do |format|
      format.html { redirect_to insta_posts_url, notice: "Insta post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_insta_post
      @insta_post = InstaPost.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def insta_post_params
      params.require(:insta_post).permit(:image)
    end
end

app/helpers/insta_posts_helper.rb
module InstaPostsHelper
end

app/views/insta_posts/_form.html.erb
<%= form_with(model: insta_post) do |form| %>
  <% if insta_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(insta_post.errors.count, "error") %> prohibited this insta_post from being saved:</h2>

      <ul>
        <% insta_post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/insta_posts/edit.html.erb
<h1>Editing Insta Post</h1>

<%= render 'form', insta_post: @insta_post %>

<%= link_to 'Show', @insta_post %> |
<%= link_to 'Back', insta_posts_path %>

app/views/insta_posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Insta Posts</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @insta_posts.each do |insta_post| %>
      <tr>
        <td><%= insta_post.image %></td>
        <td><%= link_to 'Show', insta_post %></td>
        <td><%= link_to 'Edit', edit_insta_post_path(insta_post) %></td>
        <td><%= link_to 'Destroy', insta_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Insta Post', new_insta_post_path %>

app/views/insta_posts/new.html.erb
<h1>New Insta Post</h1>

<%= render 'form', insta_post: @insta_post %>

<%= link_to 'Back', insta_posts_path %>

app/views/insta_posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= @insta_post.image %>
</p>

<%= link_to 'Edit', edit_insta_post_path(@insta_post) %> |
<%= link_to 'Back', insta_posts_path %>